require:
  - rubocop-rspec
  - rubocop-rails
AllCops:
  Exclude:
    - db/schema.rb
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
RSpec/FilePath:
  Enabled: false
  