# Overriding for vscode container running
version: "3"
services:
  web:
    command: [ "./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_rails_with_foreman.sh"]
    entrypoint: ''
    ports:
      - "3000:3000"
      - "4001:4001"
    environment:
      NODE_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PORT: 4001
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:4001
  yarn:
    image: hello-world
    command: ''
  sidekiq:
    image: hello-world
    command: ''