default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USER") { '' } %>
  password: <%= ENV.fetch("DB_PASS") { '' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_dev

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_dev